### ISSUE TITLE
Need ability to repeat single song in queue

### ISSUE THREAD

**Issue by kmckinley** [appunite/AUMediaPlayer#3]
It would be nice to have the ability to repeat a single song in a queue.  This would be in addition to the current repeat of a queue.
I've done the work and will submit a pull request.

**Comment by lukkas** [comment]
Good point. I will update the pod to your suggestions, but I'm going to change repeat BOOL property to enumeration type with three options. Therefore I will bump version to 2.0.0, since it won't be backwards compatible. Also added two methods for items-in-the-queue playback.

**Comment by kwojtaszek** [comment]
@lukkas you can bump it to 1.1.0, it will be ok

**Comment by kmckinley** [comment]
Sounds good.  I was thinking about doing a enumerated type, but was trying to preserve backwards compatibility.  
Also what three options where you thinking?  none, repeat queue, repeat song?   Not sure if this would be something you would want to support, but for my implementation I'm actually turning on both _repeat and _repeatSong.  Reason being I want to allow a user to repeat a single song, but if they hit the next button and are at the end of the list then the first item in the queue start playing.

**Comment by lukkas** [comment]
I'm going to always play next track, when playNext is called. Just like you did with with playNextForce: with YES passed as a parameter. I guess it makes most sense.

**Comment by kmckinley** [comment]
That sound good
